name: main
run-name: Build and run unit tests

on:
  push:
    branches: ["main"]
    paths:
      - "*.sh"
      - "*.rs"
      - "*.cc"
      - "Cargo.toml"
      - "CMakeLists.txt"
      - ".github/workflows/**"
  pull_request:
    branches: ["main"]
    paths:
      - "*.sh"
      - "*.rs"
      - "*.cc"
      - "Cargo.toml"
      - "CMakeLists.txt"
      - ".github/workflows/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Update packages
        run: sudo apt-get update

      - name: Install dependencies
        run: |
          sudo apt-get install -y --fix-missing \
            libpam0g-dev libgtest-dev libclang-dev cmake

      - name: Install Rust
        run: |
          which cargo && true || \
            curl --proto '=https' --tlsv1.2 -sSf \
                https://sh.rustup.rs | sh -s - -y && \
            . "$HOME/.cargo/env"

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: $GITHUB_WORKSPACE/test.sh --verbose
