name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - '**'
      - '!.github/workflows/**'
      - '.github/workflows/cmake.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**'
      - '!.github/workflows/**'
      - '.github/workflows/cmake.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: $GITHUB_WORKSPACE/test.sh --verbose
