name: Rust

on:
  push:
    branches: ["main"]
    paths:
      - "*.sh"
      - "*.rs"
      - "*.cc"
      - "Cargo.toml"
      - "CMakeLists.txt"
      - ".github/workflows/**"
  pull_request:
    branches: ["main"]
    paths:
      - "*.sh"
      - "*.rs"
      - "*.cc"
      - "Cargo.toml"
      - "CMakeLists.txt"
      - ".github/workflows/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update packages
        run: sudo apt-get update

      - name: Install dependencies
        run: >
          sudo apt-get install -y --fix-missing
              libpam0g-dev libgtest-dev

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: $GITHUB_WORKSPACE/test.sh --verbose
